export async function get({ params, request }) {
  return {
    body: JSON.stringify({
      bronze: [
        {
          name: "hallwayAD",
          message: "Architectural & Graphics Design Agency.",
          start_at: "19/4/2022",
          end_at: "19/7/2022",
          recurrent: false,
          contribution: 30,
          months: "3",
          plan: "bronze",
          probability: "1",
          url: "https://t.me/hallwayAD",
          img: "/img/sponsors/hallwayAD/squared.webp",
          webImg: "/img/sponsors/hallwayAD/wide.webp",
        },
        {
          name: "R. Baldokin",
          message: "Marketer & Social Media Manager ayudando a las Marcas a ser más relevantes en el mundo en digital.",
          start_at: "19/6/2022",
          end_at: "19/6/2023",
          recurrent: false,
          contribution: 30,
          months: "12",
          plan: "bronze",
          probability: "1",
          url: "https://t.me/KATAPVLTA",
          img: "/img/sponsors/baldokin/squared.webp",
          webImg: "/img/sponsors/baldokin/wide.webp",
        },
        {
          name: "Academia Efectivida",
          message: "Academia de desarrollo personal.",
          start_at: "18/3/2022",
          end_at: "1/2/2022",
          recurrent: false,
          contribution: 100,
          months: "12",
          plan: "bronze",
          probability: "1",
          url: "https://www.efectivida.es/",
          img: "/img/sponsors/efectivida/squared.webp",
          webImg: "/img/sponsors/efectivida/wide.webp",
        },
        {
          name: "Productiveness",
          message: "The best place to discover productivit apps",
          start_at: "18/3/2022",
          end_at: "1/2/2022",
          recurrent: false,
          contribution: 100,
          months: "12",
          plan: "bronze",
          probability: "1",
          url: "https://www.productiveness.net",
          img: "/img/sponsors/productiveness/squared.webp",
          webImg: "/img/sponsors/productiveness/wide.webp",
        },
      ],
      silver: [],
      golden: [],
      diamond: [],
    }),
  };
}
